
export const sampleData=[
    {
    id:'1',
    name:'Food1',
    price:'50',
    cookTime:'10-20',
    favorite:false,
    origins:['ethiopia'],
    stars:4.0,
    imageUrl:'download (2).jpeg',
    tags:['Lunch','Snack'],
},
{
    id:'2',
    name:'Food2',
    price:'100',
    cookTime:'20-30',
    favorite:false,
    origins:['china'],
    stars:4.1,
    imageUrl:'download (2).jpeg',
    tags:['Dinner'],
},
{
    id:'3',
    name:'Food3',
    price:'150',
    cookTime:'30-40',
    favorite:false,
    origins:['canada'],
    stars:4.0,
    imageUrl:'download (2).jpeg',
    tags:['Lunch','snack'],
},
{
    id:'4',
    name:'Food4',
    price:'200',
    cookTime:'10-20',
    favorite:false,
    origins:['sudan'],
    stars:4.5,
    imageUrl:'download (2).jpeg',
    tags:['FastFood','Breakfast'],
},
{
    id:'5',
    name:'Food5',
    price:'200',
    cookTime:'10-20',
    favorite:false,
    origins:['sudan'],
    stars:4.5,
    imageUrl:'download (2).jpeg',
    tags:['FastFood','Breakfast'],
},
{
    id:'6',
    name:'Food6',
    price:'200',
    cookTime:'10-20',
    favorite:true,
    origins:['sudan'],
    stars:4.5,
    imageUrl:'download (2).jpeg',
    tags:['FastFood','Breakfast'],
},
];
export const sampleTags=[
    {name:'All', count:20},
    {name:'FastFood', count:2},
    {name:'Breakfast', count:1},
    {name:'Lunch', count:4},
    {name:'Dinner', count:5},
    {name:'Snack', count:6},
]
//'Lunch','Dinner','Snack'